### ISSUE TITLE
This is how you use it

### ISSUE THREAD

**Issue by ghost** [surge-synthesizer/sst-waveshapers#1]
In case you want to know how

sst::waveshapers::QuadWaveshaperState    waveState;
sst::waveshapers::QuadWaveshaperPtr pWaveShaper;

pWaveShaper = sst::waveshapers::GetQuadWaveshaper(sst::waveshapers::WaveshaperType::wst_fuzz);

float * ptr = your float data;
for(size_t i = 0; i < framesPerBuffer; i+=4)
    {
        __m128 x = _mm_load_ps(tptr+i);
        __m128 gain = _mm_set1_ps(2.0f);
        pWaveShaper(&waveState,x,gain);
    }

**Comment by baconpaul** [comment]
Thanks

you will want to make sure your float data is properly aligned  and also init your state. Plus you can process parallel streams with the simd also. 

also your example will only work for the stateless shapers since you are running parallel in time, and the simd is parallel in voice. So this example will break with all the alias suppressing ones line the rectifiers and wavefolders. https://github.com/surge-synthesizer/surge/blob/84c182443cb563135b6cee29bcdac4824a5754ca/src/common/dsp/effects/WaveShaperEffect.cpp#L97

the surge quad filter bank and waveshaper effect have full examples. 

best!
